### ISSUE TITLE
Upgrade to H3 4.x

### ISSUE THREAD

**Issue by lightify97** [dfellis/h3-node#47]
I am considering using this in one of my projects. Just wanted to ask whether there is a plan to port to H3 4.x? There are some new functions in 4.x that I need. 
Thanks for the awesome work.

**Comment by dfellis** [comment]
Hey @lightify97 ,

Porting to 4.x is something I intend to do, but I have had on-and-off discussions with @nrabinowitz about potentially merging this library with [`h3-js`](https://github.com/uber/h3-js) along with an `h3-wasm` variant. Between work and an unexpected family situation, though, I haven't been able to push forward on this for a while, though.

So, if you need 4.x stuff *soon*, I'd recommend using `h3-js`, which also works in Node just fine, since I'm not sure when I'll be able to update.

**Comment by dfellis** [comment]
[`h3-node` v4.1.0 is now published.](https://www.npmjs.com/package/h3-node)

It doesn't have the vertex mode functions, yet. That will be a follow-up PR.
